### ISSUE TITLE
Create a easy way to find webApp context.

### ISSUE THREAD

**Issue by vijaykumar95489** [aleon1220/multi-cloud-AttendWebApp#7]
URL should include the context so that web application is easy to access.

**Comment by aleon1220** [comment]
Yes, i worked in this and updated the Readme file in a feature/branch. 
Next is to do a git cherry pick from the develop branch to the main branch.

**Comment by aleon1220** [comment]
@vijaykumar95489  

- the quick start offers the option to get the app version which is part of the context.
- Also i added an environment variable below to create the Full URL with the context
```bash
TOMCAT_URL="http://$(hostname):8080/Attendance-$APP_WAR_FILE_VERSION"
```

**Comment by aleon1220** [comment]
Future work involves adding functions to the gradle build file to optimize this.
